### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by thankgodr**
- Created a clone page of apple.com archived page.

- installed Stickler for stylesheet linting

- validated HTML using w3.org validator

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### Good work you have done so far, impressive. However, there are changes you are required to make for your project to be approved.

- Make your navigation look like the reference [website](https://web.archive.org/web/20140301004610/http://www.apple.com/), especially the gradient and the background color combination
- Avoid the use of the keyword `!important` in your CSS file
- Adjust your footer to look better, reduce the spacing and make the `font-size` smaller 

### Once you have made all these changes, resubmit for another review. I wish you all the best in your next submission.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really great job @thankgodr! :handshake: 
Your project is really coming together, however, there is one small change you need to make to tie it all together. The images in the footer section of the site are to be of the same width, however, every image seems either too short or too long. Please see a screenshot below: 
screenshot

### Summary
This is a really wonderful job, please look into the one detail highlighted above, make appropriate adjustments and submit for another review!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work with the minor adjustments :muscle: 
Please be adviced that all the image containers need to be the same width. The last image is much smaller than the previous three. Kindly look into this and make final corrections!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by thankgodr** [comment]
> # Nice work with the minor adjustments 💪
> Please be adviced that all the image containers need to be the same width. The last image is much smaller than the previous three. Kindly look into this and make final corrections!
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

I  was unable to figure out which container. I gave each of the container flex: 1. also did inspect my code and found each div containing the image to be the same height and length.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @thankgodr :clap: , the last image is still not in order. It overflows the page**

We need to have that fixed before the project can be approved. Consider reducing the width of the images so that they are all contained within the page.

image

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE) :woman_technologist:

### Hello @thankgodr :guitar: 

### I see you've made the requested changes asked by previous reviewers, I believe your project looks even more similar to the original that it was before :art:  I have a couple of suggestions for you:

[OPTIONAL] Create a Live demo of your project by following these [steps](https://help.github.com/en/enterprise/2.13/user/articles/configuring-a-publishing-source-for-github-pages) and add it to your Readme file
 
For future projects remember to use \<div\> tags only for styling purposes they should be inside a semantic HTML tag: \<section\>, \<article\>, \<header\>, \<nav\>, \<aside\>, etc.

### That's it. Congratulations on this project :star: make this Optional change :memo: and submit the project no need to request for a code review :rocket: 
STATUS OF THE PROJECT: APPROVED :green_apple:

**Pull request merged**
